name: Node.js CI - Run Tests

on:
  push:
    branches: [ main ]  # Trigger when pushing to main
  pull_request:
    branches: [ main ]  # Trigger on pull requests to main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test
